# services:
#   sqlserver:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     ports:
#       - "1433:1433"
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD=12345678
#       - MSSQL_PID=Express
#     volumes:
#       - sqlserver_data:/var/opt/mssql

#   minio:
#     image: minio/minio:latest
#     container_name: minio
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     environment:
#       MINIO_ROOT_USER: admin
#       MINIO_ROOT_PASSWORD: 12345678
#     command: server /data --console-address ":9001"
#     volumes:
#       - minio_data:/data

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     ports:
#       - "3000:3000"
#     volumes:
#       - grafana_data:/var/lib/grafana
#     # note : login grafana always:
#     # username:   admin
#     # pass:       admin

#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml

#   web-restaurant:
#     image: zyond/cicd:latest
#     container_name: web-restaurant
#     ports:
#       - "5000:5000"
#     environment:
#       - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=WebRestaurant12;User Id=sa;Password=12345678;

# volumes:
#   minio_data:
#   grafana_data:
#   sqlserver_data:

version: '3.8'

#  work with traefik
services:

  traefik:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - "80:80" # HTTP
      - "8080:8080" # Traefik dashboard
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=12345678
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - traefik-net

  web-restaurant:
    container_name: web-restaurant
    image: zyond/cicd:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - traefik-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks:
      - traefik-net

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    labels:
      - "traefik.enable=true" # API MinIO (9000)
      - "traefik.http.routers.minio.rule=Host(`minio.localhost`)"
      - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.routers.minio.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"

      # Console UI (9001)
      - "traefik.http.routers.minio-console.rule=Host(`minio-console.localhost`)"
      - "traefik.http.routers.minio-console.entrypoints=web"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
    networks:
      - traefik-net

volumes:
  sqlserver_data:
  grafana_data:
  minio_data:


networks:
  traefik-net:
    name: traefik-net
    driver: bridge
