# global:
#   scrape_interval: 5s

# scrape_configs:
#   - job_name: 'docker'
#     static_configs:
#       - targets: ['host.docker.internal:9090']

 
#   - job_name: 'web_restaurant'
#     static_configs:
#       - targets: ['web_restaurant:5000'] # Đảm bảo tên dịch vụ khớp với tên trong docker-compose.yml

      
#   - job_name: 'jenkins'
#     static_configs:
#       - targets: ['host.docker.internal:8099']


global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'web_restaurant'
    static_configs:
      - targets: ['web-restaurant-service:80']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio-service:9000']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana-service:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-service:9090']

  