global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'web-restaurant'
    static_configs:
      - targets: ['web-restaurant:5000']
        metrics_path: '/metrics'

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
        metrics_path: '/minio/v2/metrics/cluster'
        basic_auth:
          username: admin
          password: 12345678