apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-restaurant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-restaurant
  template:
    metadata:
      labels:
        app: web-restaurant
    spec:
      containers:
      - name: web-restaurant
        image: zyond/cicd:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-restaurant-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web-restaurant
  type: LoadBalancer